// Code generated by MockGen. DO NOT EDIT.
// Source: runner.go
//
// Generated by this command:
//
//	mockgen -source=runner.go -destination=mock_executor_test.go -package=agent_test
//

// Package agent_test is a generated GoMock package.
package agent_test

import (
	context "context"
	reflect "reflect"

	agent "github.com/candacelabs/candace/app/candaceos-agent/internal/agent"
	candaceosv1 "github.com/candacelabs/candace/proto/candace/candaceos/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockExecutor is a mock of Executor interface.
type MockExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockExecutorMockRecorder
	isgomock struct{}
}

// MockExecutorMockRecorder is the mock recorder for MockExecutor.
type MockExecutorMockRecorder struct {
	mock *MockExecutor
}

// NewMockExecutor creates a new mock instance.
func NewMockExecutor(ctrl *gomock.Controller) *MockExecutor {
	mock := &MockExecutor{ctrl: ctrl}
	mock.recorder = &MockExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExecutor) EXPECT() *MockExecutorMockRecorder {
	return m.recorder
}

// DryRun mocks base method.
func (m *MockExecutor) DryRun() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DryRun")
	ret0, _ := ret[0].(bool)
	return ret0
}

// DryRun indicates an expected call of DryRun.
func (mr *MockExecutorMockRecorder) DryRun() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DryRun", reflect.TypeOf((*MockExecutor)(nil).DryRun))
}

// Execute mocks base method.
func (m *MockExecutor) Execute(ctx context.Context, plan agent.Plan) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, plan)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockExecutorMockRecorder) Execute(ctx, plan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockExecutor)(nil).Execute), ctx, plan)
}

// Plan mocks base method.
func (m *MockExecutor) Plan(ctx context.Context, assignment *candaceosv1.Assignment) (agent.Plan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Plan", ctx, assignment)
	ret0, _ := ret[0].(agent.Plan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Plan indicates an expected call of Plan.
func (mr *MockExecutorMockRecorder) Plan(ctx, assignment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Plan", reflect.TypeOf((*MockExecutor)(nil).Plan), ctx, assignment)
}

// Workspace mocks base method.
func (m *MockExecutor) Workspace() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Workspace")
	ret0, _ := ret[0].(string)
	return ret0
}

// Workspace indicates an expected call of Workspace.
func (mr *MockExecutorMockRecorder) Workspace() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Workspace", reflect.TypeOf((*MockExecutor)(nil).Workspace))
}

// MockComposeProcessExecutor is a mock of ComposeProcessExecutor interface.
type MockComposeProcessExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockComposeProcessExecutorMockRecorder
	isgomock struct{}
}

// MockComposeProcessExecutorMockRecorder is the mock recorder for MockComposeProcessExecutor.
type MockComposeProcessExecutorMockRecorder struct {
	mock *MockComposeProcessExecutor
}

// NewMockComposeProcessExecutor creates a new mock instance.
func NewMockComposeProcessExecutor(ctrl *gomock.Controller) *MockComposeProcessExecutor {
	mock := &MockComposeProcessExecutor{ctrl: ctrl}
	mock.recorder = &MockComposeProcessExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockComposeProcessExecutor) EXPECT() *MockComposeProcessExecutorMockRecorder {
	return m.recorder
}

// Resolve mocks base method.
func (m *MockComposeProcessExecutor) Resolve(executable string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", executable)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *MockComposeProcessExecutorMockRecorder) Resolve(executable any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockComposeProcessExecutor)(nil).Resolve), executable)
}

// Run mocks base method.
func (m *MockComposeProcessExecutor) Run(ctx context.Context, invocation agent.ComposeInvocation) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx, invocation)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Run indicates an expected call of Run.
func (mr *MockComposeProcessExecutorMockRecorder) Run(ctx, invocation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockComposeProcessExecutor)(nil).Run), ctx, invocation)
}
