// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/candacelabs/candace/services/warden (interfaces: Transport,Notifier,Store,Clock,PeerDiscoverer,ViewSource,IncidentLog,RPCHandler)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mocks.go -package=mocks github.com/candacelabs/candace/services/warden Transport,Notifier,Store,Clock,PeerDiscoverer,ViewSource,IncidentLog,RPCHandler
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	warden "github.com/candacelabs/candace/services/warden"
	gomock "go.uber.org/mock/gomock"
)

// MockTransport is a mock of Transport interface.
type MockTransport struct {
	ctrl     *gomock.Controller
	recorder *MockTransportMockRecorder
	isgomock struct{}
}

// MockTransportMockRecorder is the mock recorder for MockTransport.
type MockTransportMockRecorder struct {
	mock *MockTransport
}

// NewMockTransport creates a new mock instance.
func NewMockTransport(ctrl *gomock.Controller) *MockTransport {
	mock := &MockTransport{ctrl: ctrl}
	mock.recorder = &MockTransportMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransport) EXPECT() *MockTransportMockRecorder {
	return m.recorder
}

// Identify mocks base method.
func (m *MockTransport) Identify(ctx context.Context, peer warden.Node) (warden.IdentifyResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Identify", ctx, peer)
	ret0, _ := ret[0].(warden.IdentifyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Identify indicates an expected call of Identify.
func (mr *MockTransportMockRecorder) Identify(ctx, peer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Identify", reflect.TypeOf((*MockTransport)(nil).Identify), ctx, peer)
}

// RequestVote mocks base method.
func (m *MockTransport) RequestVote(ctx context.Context, peer warden.Node, req warden.VoteRequest) (warden.VoteResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestVote", ctx, peer, req)
	ret0, _ := ret[0].(warden.VoteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RequestVote indicates an expected call of RequestVote.
func (mr *MockTransportMockRecorder) RequestVote(ctx, peer, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestVote", reflect.TypeOf((*MockTransport)(nil).RequestVote), ctx, peer, req)
}

// SendHeartbeat mocks base method.
func (m *MockTransport) SendHeartbeat(ctx context.Context, peer warden.Node, req warden.HeartbeatRequest) (warden.HeartbeatResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendHeartbeat", ctx, peer, req)
	ret0, _ := ret[0].(warden.HeartbeatResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendHeartbeat indicates an expected call of SendHeartbeat.
func (mr *MockTransportMockRecorder) SendHeartbeat(ctx, peer, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendHeartbeat", reflect.TypeOf((*MockTransport)(nil).SendHeartbeat), ctx, peer, req)
}

// MockNotifier is a mock of Notifier interface.
type MockNotifier struct {
	ctrl     *gomock.Controller
	recorder *MockNotifierMockRecorder
	isgomock struct{}
}

// MockNotifierMockRecorder is the mock recorder for MockNotifier.
type MockNotifierMockRecorder struct {
	mock *MockNotifier
}

// NewMockNotifier creates a new mock instance.
func NewMockNotifier(ctrl *gomock.Controller) *MockNotifier {
	mock := &MockNotifier{ctrl: ctrl}
	mock.recorder = &MockNotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotifier) EXPECT() *MockNotifierMockRecorder {
	return m.recorder
}

// Notify mocks base method.
func (m *MockNotifier) Notify(ctx context.Context, inc warden.Incident) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Notify", ctx, inc)
	ret0, _ := ret[0].(error)
	return ret0
}

// Notify indicates an expected call of Notify.
func (mr *MockNotifierMockRecorder) Notify(ctx, inc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Notify", reflect.TypeOf((*MockNotifier)(nil).Notify), ctx, inc)
}

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// Load mocks base method.
func (m *MockStore) Load() (warden.PersistentState, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load")
	ret0, _ := ret[0].(warden.PersistentState)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Load indicates an expected call of Load.
func (mr *MockStoreMockRecorder) Load() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockStore)(nil).Load))
}

// Save mocks base method.
func (m *MockStore) Save(st warden.PersistentState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", st)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockStoreMockRecorder) Save(st any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockStore)(nil).Save), st)
}

// MockClock is a mock of Clock interface.
type MockClock struct {
	ctrl     *gomock.Controller
	recorder *MockClockMockRecorder
	isgomock struct{}
}

// MockClockMockRecorder is the mock recorder for MockClock.
type MockClockMockRecorder struct {
	mock *MockClock
}

// NewMockClock creates a new mock instance.
func NewMockClock(ctrl *gomock.Controller) *MockClock {
	mock := &MockClock{ctrl: ctrl}
	mock.recorder = &MockClockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClock) EXPECT() *MockClockMockRecorder {
	return m.recorder
}

// After mocks base method.
func (m *MockClock) After(d time.Duration) <-chan time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "After", d)
	ret0, _ := ret[0].(<-chan time.Time)
	return ret0
}

// After indicates an expected call of After.
func (mr *MockClockMockRecorder) After(d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "After", reflect.TypeOf((*MockClock)(nil).After), d)
}

// NewTicker mocks base method.
func (m *MockClock) NewTicker(d time.Duration) warden.Ticker {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewTicker", d)
	ret0, _ := ret[0].(warden.Ticker)
	return ret0
}

// NewTicker indicates an expected call of NewTicker.
func (mr *MockClockMockRecorder) NewTicker(d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewTicker", reflect.TypeOf((*MockClock)(nil).NewTicker), d)
}

// NewTimer mocks base method.
func (m *MockClock) NewTimer(d time.Duration) warden.Timer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewTimer", d)
	ret0, _ := ret[0].(warden.Timer)
	return ret0
}

// NewTimer indicates an expected call of NewTimer.
func (mr *MockClockMockRecorder) NewTimer(d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewTimer", reflect.TypeOf((*MockClock)(nil).NewTimer), d)
}

// Now mocks base method.
func (m *MockClock) Now() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Now")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Now indicates an expected call of Now.
func (mr *MockClockMockRecorder) Now() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Now", reflect.TypeOf((*MockClock)(nil).Now))
}

// MockPeerDiscoverer is a mock of PeerDiscoverer interface.
type MockPeerDiscoverer struct {
	ctrl     *gomock.Controller
	recorder *MockPeerDiscovererMockRecorder
	isgomock struct{}
}

// MockPeerDiscovererMockRecorder is the mock recorder for MockPeerDiscoverer.
type MockPeerDiscovererMockRecorder struct {
	mock *MockPeerDiscoverer
}

// NewMockPeerDiscoverer creates a new mock instance.
func NewMockPeerDiscoverer(ctrl *gomock.Controller) *MockPeerDiscoverer {
	mock := &MockPeerDiscoverer{ctrl: ctrl}
	mock.recorder = &MockPeerDiscovererMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPeerDiscoverer) EXPECT() *MockPeerDiscovererMockRecorder {
	return m.recorder
}

// Discover mocks base method.
func (m *MockPeerDiscoverer) Discover(ctx context.Context) (<-chan warden.Roster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Discover", ctx)
	ret0, _ := ret[0].(<-chan warden.Roster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Discover indicates an expected call of Discover.
func (mr *MockPeerDiscovererMockRecorder) Discover(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Discover", reflect.TypeOf((*MockPeerDiscoverer)(nil).Discover), ctx)
}

// MockViewSource is a mock of ViewSource interface.
type MockViewSource struct {
	ctrl     *gomock.Controller
	recorder *MockViewSourceMockRecorder
	isgomock struct{}
}

// MockViewSourceMockRecorder is the mock recorder for MockViewSource.
type MockViewSourceMockRecorder struct {
	mock *MockViewSource
}

// NewMockViewSource creates a new mock instance.
func NewMockViewSource(ctrl *gomock.Controller) *MockViewSource {
	mock := &MockViewSource{ctrl: ctrl}
	mock.recorder = &MockViewSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockViewSource) EXPECT() *MockViewSourceMockRecorder {
	return m.recorder
}

// Subscribe mocks base method.
func (m *MockViewSource) Subscribe(buf int) (<-chan warden.ClusterView, func()) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", buf)
	ret0, _ := ret[0].(<-chan warden.ClusterView)
	ret1, _ := ret[1].(func())
	return ret0, ret1
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockViewSourceMockRecorder) Subscribe(buf any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockViewSource)(nil).Subscribe), buf)
}

// View mocks base method.
func (m *MockViewSource) View() warden.ClusterView {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "View")
	ret0, _ := ret[0].(warden.ClusterView)
	return ret0
}

// View indicates an expected call of View.
func (mr *MockViewSourceMockRecorder) View() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "View", reflect.TypeOf((*MockViewSource)(nil).View))
}

// MockIncidentLog is a mock of IncidentLog interface.
type MockIncidentLog struct {
	ctrl     *gomock.Controller
	recorder *MockIncidentLogMockRecorder
	isgomock struct{}
}

// MockIncidentLogMockRecorder is the mock recorder for MockIncidentLog.
type MockIncidentLogMockRecorder struct {
	mock *MockIncidentLog
}

// NewMockIncidentLog creates a new mock instance.
func NewMockIncidentLog(ctrl *gomock.Controller) *MockIncidentLog {
	mock := &MockIncidentLog{ctrl: ctrl}
	mock.recorder = &MockIncidentLogMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIncidentLog) EXPECT() *MockIncidentLogMockRecorder {
	return m.recorder
}

// Incidents mocks base method.
func (m *MockIncidentLog) Incidents() []warden.Incident {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Incidents")
	ret0, _ := ret[0].([]warden.Incident)
	return ret0
}

// Incidents indicates an expected call of Incidents.
func (mr *MockIncidentLogMockRecorder) Incidents() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Incidents", reflect.TypeOf((*MockIncidentLog)(nil).Incidents))
}

// MockRPCHandler is a mock of RPCHandler interface.
type MockRPCHandler struct {
	ctrl     *gomock.Controller
	recorder *MockRPCHandlerMockRecorder
	isgomock struct{}
}

// MockRPCHandlerMockRecorder is the mock recorder for MockRPCHandler.
type MockRPCHandlerMockRecorder struct {
	mock *MockRPCHandler
}

// NewMockRPCHandler creates a new mock instance.
func NewMockRPCHandler(ctrl *gomock.Controller) *MockRPCHandler {
	mock := &MockRPCHandler{ctrl: ctrl}
	mock.recorder = &MockRPCHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRPCHandler) EXPECT() *MockRPCHandlerMockRecorder {
	return m.recorder
}

// HandleHeartbeat mocks base method.
func (m *MockRPCHandler) HandleHeartbeat(ctx context.Context, req warden.HeartbeatRequest) warden.HeartbeatResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleHeartbeat", ctx, req)
	ret0, _ := ret[0].(warden.HeartbeatResponse)
	return ret0
}

// HandleHeartbeat indicates an expected call of HandleHeartbeat.
func (mr *MockRPCHandlerMockRecorder) HandleHeartbeat(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleHeartbeat", reflect.TypeOf((*MockRPCHandler)(nil).HandleHeartbeat), ctx, req)
}

// HandleIdentify mocks base method.
func (m *MockRPCHandler) HandleIdentify(ctx context.Context) warden.IdentifyResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleIdentify", ctx)
	ret0, _ := ret[0].(warden.IdentifyResponse)
	return ret0
}

// HandleIdentify indicates an expected call of HandleIdentify.
func (mr *MockRPCHandlerMockRecorder) HandleIdentify(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleIdentify", reflect.TypeOf((*MockRPCHandler)(nil).HandleIdentify), ctx)
}

// HandleVote mocks base method.
func (m *MockRPCHandler) HandleVote(ctx context.Context, req warden.VoteRequest) warden.VoteResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleVote", ctx, req)
	ret0, _ := ret[0].(warden.VoteResponse)
	return ret0
}

// HandleVote indicates an expected call of HandleVote.
func (mr *MockRPCHandlerMockRecorder) HandleVote(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleVote", reflect.TypeOf((*MockRPCHandler)(nil).HandleVote), ctx, req)
}
