// Code generated by pkg/widget/internal/uigen from the NodeStatus widget document. DO NOT EDIT.

// Package nodestatus is the generated NodeStatus widget.
//
// Edit the widget document and regenerate; edits here are overwritten.
package nodestatus

import (
	"context"
	"fmt"
	"strconv"

	"github.com/a-h/templ"

	"github.com/candacelabs/candace/pkg/gotth/live"
	"github.com/candacelabs/candace/pkg/widget"
)

// This widget's identity. The region is the only one that crosses the wire: a
// patch names it, so changing it is a client-visible change. The palette is a
// name a host resolves to values; this widget carries no colour of its own.
// The title id is what the widget's landmark is labelled by.
const (
	NodeStatusName    = "NodeStatus"
	NodeStatusRegion  = "widget.node-status"
	NodeStatusPalette = "fieldStation"
	NodeStatusTitleID = "widget.node-status-title"
)

// The wire names this widget accepts. The set is exhaustive and default-deny:
// a name absent from the registration is refused before any reducer runs.
const (
	NodeStatusEventHealth = "widget.node-status.health"
)

// The wire field names each event carries. They are the other half of an
// event's contract: the widget reads these out of a delivery, and whatever
// produced the delivery wrote them in. Registration.Payloads carries the same
// names as data, for a host that fills an event it cannot name at compile time.
const (
	NodeStatusEventHealthFieldReachable = "reachable"
)

// NodeStatusState is this widget's own state, and the type argument every
// method below is written in. The host holds it without knowing it; nothing
// in this file asserts it back, because nothing in this file ever loses it.
type NodeStatusState struct {
	// Reachable is the "reachable" state field, declared type flag.
	Reachable bool
}

// NodeStatus is the generated NodeStatus widget.
type NodeStatus struct{}

// NewNodeStatus returns the widget a host registers.
func NewNodeStatus() *NodeStatus { return &NodeStatus{} }

var (
	_ widget.IWidget[NodeStatusState]        = (*NodeStatus)(nil)
	_ widget.IDirtyDeclarer[NodeStatusState] = (*NodeStatus)(nil)
)

// Register declares the widget, once per process and before any session.
//
// Events are the names a browser may send; Internal are the names only a
// declared stream delivers, which the host routes without registering.
func (instance *NodeStatus) Register() widget.Registration {
	return widget.Registration{
		Name:     NodeStatusName,
		Region:   NodeStatusRegion,
		Internal: []string{NodeStatusEventHealth},
		Streams: []widget.StreamDeclaration{
			{Name: "healthWatch", Source: "widget.node-status.watch", Delivers: NodeStatusEventHealth},
		},
		Payloads: []widget.EventPayload{
			{Event: NodeStatusEventHealth, Fields: []string{
				NodeStatusEventHealthFieldReachable,
			}},
		},
	}
}

// Mount opens one session's copy of the widget. It schedules no effect: the
// streams this widget declared are the host's to open, because a widget document
// names no host, no address and no credential.
func (instance *NodeStatus) Mount(
	ctx context.Context, session live.Session,
) (NodeStatusState, []live.IEffect, error) {
	return NodeStatusState{}, nil, nil
}

// Reduce is the pure transition from one state to the next. It performs no I/O,
// reads no clock and mutates nothing it was given.
func (instance *NodeStatus) Reduce(
	state NodeStatusState, event live.Event,
) (NodeStatusState, []live.IEffect) {
	current := state
	switch event.Name {
	case NodeStatusEventHealth:
		if raw, present := event.Fields.Lookup(NodeStatusEventHealthFieldReachable); present {
			current.Reachable = widget.ParseFlag(raw, current.Reachable)
		}
	}
	return current, nil
}

// Render draws the widget's live region. It is a pure function of state:
// equal state renders byte-identical markup.
func (instance *NodeStatus) Render(state NodeStatusState) templ.Component {
	return NodeStatusView(state)
}

// Dirty reports whether a transition may have changed this widget's markup: the
// state fields its bindings, its predicates and its tick read, and no others.
func (instance *NodeStatus) Dirty(previous NodeStatusState, next NodeStatusState) bool {
	return previous.Reachable != next.Reachable
}

// Effect performs an effect this widget scheduled. It schedules none, so an
// effect arriving here was routed wrongly — which is reported rather than
// silently succeeded at, because an effect that never runs is a change that
// never happens.
func (instance *NodeStatus) Effect(
	ctx context.Context, session live.Session, effect live.IEffect, emit live.Emitter,
) error {
	return fmt.Errorf("%s: schedules no effect, but %s arrived", NodeStatusName, effect.EffectSource())
}

// Unmount releases what the session held. This widget holds nothing.
func (instance *NodeStatus) Unmount(ctx context.Context, session live.Session, state NodeStatusState) {
}

// Snapshot projects state into ordered name/value pairs, in state-field
// declaration order.
func (instance *NodeStatus) Snapshot(state NodeStatusState) widget.Snapshot {
	return widget.Snapshot{
		Widget: NodeStatusName,
		Fields: []widget.SnapshotField{
			{Name: "reachable", Value: strconv.FormatBool(state.Reachable)},
		},
	}
}

// StatusText is the "statusText" binding. The first matching clause wins and the
// otherwise arm is always present, so it is total.
func (state NodeStatusState) StatusText() string {
	if state.Reachable {
		return "reachable"
	}
	return "unreachable"
}

// SceneDescriptionText is the "sceneDescriptionText" binding. The first matching clause wins and the
// otherwise arm is always present, so it is total.
func (state NodeStatusState) SceneDescriptionText() string {
	if state.Reachable {
		return "One node; its health check is passing."
	}
	return "One node; its health check is failing."
}

// TitleLabel is the "titleLabel" label.
func (state NodeStatusState) TitleLabel() string {
	return "Node status"
}

// SceneDescriptionLabel is the "sceneDescriptionLabel" label.
func (state NodeStatusState) SceneDescriptionLabel() string {
	return state.SceneDescriptionText()
}

// NodeALabel is the "nodeALabel" label.
func (state NodeStatusState) NodeALabel() string {
	return "node-a"
}

// StatusLabel is the "statusLabel" label.
func (state NodeStatusState) StatusLabel() string {
	return state.StatusText()
}
