// Code generated by protoc-gen-liquidproto. DO NOT EDIT.
// versions:
// 	protoc-gen-liquidproto v0.1.0
// 	protoc                 v7.35.1
// source: widget/refinement/v1/refinement.proto

package widgetrefinementv1

import (
	fmt "fmt"
	liquidproto "github.com/candacelabs/candace/pkg/liquidproto"
	regexp "regexp"
)

var (
	_liquidRegionIdentityValueRe0     = regexp.MustCompile("^[A-Za-z0-9_:.-]{1,64}$")
	_liquidWireNameValueRe0           = regexp.MustCompile("^[^:;]+$")
	_liquidEventFieldWireNameValueRe0 = regexp.MustCompile("^[a-z][a-z0-9]*(_[a-z0-9]+)*$")
	_liquidIdentifierValueRe0         = regexp.MustCompile("^[a-z][A-Za-z0-9]*$")
)

// ValidateRegionIdentity validates Liquid Proto field predicates.
func ValidateRegionIdentity(message *RegionIdentity) error {
	if message == nil {
		return fmt.Errorf("ValidateRegionIdentity: nil *RegionIdentity")
	}
	if !(_liquidRegionIdentityValueRe0.MatchString(message.Value)) {
		return &liquidproto.Error{
			Message:   "candace.widget.refinement.v1.RegionIdentity",
			Field:     "value",
			Predicate: "matches(this, `^[A-Za-z0-9_:.-]{1,64}$`)",
			Value:     message.Value,
		}
	}
	return nil
}

// ValidatePlacement validates Liquid Proto field predicates.
func ValidatePlacement(message *Placement) error {
	if message == nil {
		return fmt.Errorf("ValidatePlacement: nil *Placement")
	}
	if !(message.Left >= 0 && message.Left <= 100) {
		return &liquidproto.Error{
			Message:   "candace.widget.refinement.v1.Placement",
			Field:     "left",
			Predicate: "this >= 0 && this <= 100",
			Value:     message.Left,
		}
	}
	if !(message.Top >= 0 && message.Top <= 100) {
		return &liquidproto.Error{
			Message:   "candace.widget.refinement.v1.Placement",
			Field:     "top",
			Predicate: "this >= 0 && this <= 100",
			Value:     message.Top,
		}
	}
	return nil
}

// ValidatePulseTiming validates Liquid Proto field predicates.
func ValidatePulseTiming(message *PulseTiming) error {
	if message == nil {
		return fmt.Errorf("ValidatePulseTiming: nil *PulseTiming")
	}
	if !(message.DurationMilliseconds > 0) {
		return &liquidproto.Error{
			Message:   "candace.widget.refinement.v1.PulseTiming",
			Field:     "duration_milliseconds",
			Predicate: "this > 0",
			Value:     message.DurationMilliseconds,
		}
	}
	if !(message.DelayMilliseconds >= 0) {
		return &liquidproto.Error{
			Message:   "candace.widget.refinement.v1.PulseTiming",
			Field:     "delay_milliseconds",
			Predicate: "this >= 0",
			Value:     message.DelayMilliseconds,
		}
	}
	return nil
}

// ValidateEmphasisTiming validates Liquid Proto field predicates.
func ValidateEmphasisTiming(message *EmphasisTiming) error {
	if message == nil {
		return fmt.Errorf("ValidateEmphasisTiming: nil *EmphasisTiming")
	}
	if !(message.DurationMilliseconds > 0) {
		return &liquidproto.Error{
			Message:   "candace.widget.refinement.v1.EmphasisTiming",
			Field:     "duration_milliseconds",
			Predicate: "this > 0",
			Value:     message.DurationMilliseconds,
		}
	}
	if !(message.DelayMilliseconds >= 0) {
		return &liquidproto.Error{
			Message:   "candace.widget.refinement.v1.EmphasisTiming",
			Field:     "delay_milliseconds",
			Predicate: "this >= 0",
			Value:     message.DelayMilliseconds,
		}
	}
	return nil
}

// ValidateWireName validates Liquid Proto field predicates.
func ValidateWireName(message *WireName) error {
	if message == nil {
		return fmt.Errorf("ValidateWireName: nil *WireName")
	}
	if !(_liquidWireNameValueRe0.MatchString(message.Value)) {
		return &liquidproto.Error{
			Message:   "candace.widget.refinement.v1.WireName",
			Field:     "value",
			Predicate: "matches(this, `^[^:;]+$`)",
			Value:     message.Value,
		}
	}
	return nil
}

// ValidateEventFieldWireName validates Liquid Proto field predicates.
func ValidateEventFieldWireName(message *EventFieldWireName) error {
	if message == nil {
		return fmt.Errorf("ValidateEventFieldWireName: nil *EventFieldWireName")
	}
	if !(_liquidEventFieldWireNameValueRe0.MatchString(message.Value)) {
		return &liquidproto.Error{
			Message:   "candace.widget.refinement.v1.EventFieldWireName",
			Field:     "value",
			Predicate: "matches(this, `^[a-z][a-z0-9]*(_[a-z0-9]+)*$`)",
			Value:     message.Value,
		}
	}
	return nil
}

// ValidateIdentifier validates Liquid Proto field predicates.
func ValidateIdentifier(message *Identifier) error {
	if message == nil {
		return fmt.Errorf("ValidateIdentifier: nil *Identifier")
	}
	if !(_liquidIdentifierValueRe0.MatchString(message.Value)) {
		return &liquidproto.Error{
			Message:   "candace.widget.refinement.v1.Identifier",
			Field:     "value",
			Predicate: "matches(this, `^[a-z][A-Za-z0-9]*$`)",
			Value:     message.Value,
		}
	}
	return nil
}

// ValidateTokenValue validates Liquid Proto field predicates.
func ValidateTokenValue(message *TokenValue) error {
	if message == nil {
		return fmt.Errorf("ValidateTokenValue: nil *TokenValue")
	}
	if !(message.Value >= 1 && message.Value <= 7) {
		return &liquidproto.Error{
			Message:   "candace.widget.refinement.v1.TokenValue",
			Field:     "value",
			Predicate: "this >= 1 && this <= 7",
			Value:     message.Value,
		}
	}
	return nil
}

// ValidateMarkerValue validates Liquid Proto field predicates.
func ValidateMarkerValue(message *MarkerValue) error {
	if message == nil {
		return fmt.Errorf("ValidateMarkerValue: nil *MarkerValue")
	}
	if !(message.Value >= 1 && message.Value <= 2) {
		return &liquidproto.Error{
			Message:   "candace.widget.refinement.v1.MarkerValue",
			Field:     "value",
			Predicate: "this >= 1 && this <= 2",
			Value:     message.Value,
		}
	}
	return nil
}

// ValidateDirectionValue validates Liquid Proto field predicates.
func ValidateDirectionValue(message *DirectionValue) error {
	if message == nil {
		return fmt.Errorf("ValidateDirectionValue: nil *DirectionValue")
	}
	if !(message.Value >= 1 && message.Value <= 2) {
		return &liquidproto.Error{
			Message:   "candace.widget.refinement.v1.DirectionValue",
			Field:     "value",
			Predicate: "this >= 1 && this <= 2",
			Value:     message.Value,
		}
	}
	return nil
}

// ValidateTriggerValue validates Liquid Proto field predicates.
func ValidateTriggerValue(message *TriggerValue) error {
	if message == nil {
		return fmt.Errorf("ValidateTriggerValue: nil *TriggerValue")
	}
	if !(message.Value >= 1 && message.Value <= 4) {
		return &liquidproto.Error{
			Message:   "candace.widget.refinement.v1.TriggerValue",
			Field:     "value",
			Predicate: "this >= 1 && this <= 4",
			Value:     message.Value,
		}
	}
	return nil
}

// ValidateFieldTypeValue validates Liquid Proto field predicates.
func ValidateFieldTypeValue(message *FieldTypeValue) error {
	if message == nil {
		return fmt.Errorf("ValidateFieldTypeValue: nil *FieldTypeValue")
	}
	if !(message.Value >= 1 && message.Value <= 4) {
		return &liquidproto.Error{
			Message:   "candace.widget.refinement.v1.FieldTypeValue",
			Field:     "value",
			Predicate: "this >= 1 && this <= 4",
			Value:     message.Value,
		}
	}
	return nil
}
