// Code generated by protoc-gen-liquidproto. DO NOT EDIT.
// versions:
// 	protoc-gen-liquidproto v0.1.0
// 	protoc                 v7.35.1
// source: gotthlive/v1/frame.proto

package gotthlivepb

import (
	fmt "fmt"
	liquidproto "github.com/candacelabs/candace/pkg/liquidproto"
	regexp "regexp"
)

var (
	_liquidEventNameRe0                = regexp.MustCompile("^[a-z][a-z0-9_.:-]*$")
	_liquidEventFragmentIdRe0          = regexp.MustCompile("^[A-Za-z0-9_:.-]+$")
	_liquidEventFieldKeyRe0            = regexp.MustCompile("^[A-Za-z0-9_.\\[\\]-]+$")
	_liquidFragmentUpdateFragmentIdRe0 = regexp.MustCompile("^[A-Za-z0-9_:.-]+$")
	_liquidOriginSourceRe0             = regexp.MustCompile("^[a-z][a-z0-9_.:/-]*$")
)

// ValidateFrame validates Liquid Proto field predicates.
func ValidateFrame(message *Frame) error {
	if message == nil {
		return fmt.Errorf("ValidateFrame: nil *Frame")
	}
	if !(message.ProtocolVersion > 0) {
		return &liquidproto.Error{
			Message:   "gotthlive.v1.Frame",
			Field:     "protocol_version",
			Predicate: "this > 0",
			Value:     message.ProtocolVersion,
		}
	}
	if !(len(message.SessionId) == 16) {
		return &liquidproto.Error{
			Message:   "gotthlive.v1.Frame",
			Field:     "session_id",
			Predicate: "len(this) == 16",
			Value:     message.SessionId,
		}
	}
	return nil
}

// ValidateEvent validates Liquid Proto field predicates.
func ValidateEvent(message *Event) error {
	if message == nil {
		return fmt.Errorf("ValidateEvent: nil *Event")
	}
	if !(message.ClientRef > 0) {
		return &liquidproto.Error{
			Message:   "gotthlive.v1.Event",
			Field:     "client_ref",
			Predicate: "this > 0",
			Value:     message.ClientRef,
		}
	}
	if !(len(message.Name) > 0 && len(message.Name) <= 64 && _liquidEventNameRe0.MatchString(message.Name)) {
		return &liquidproto.Error{
			Message:   "gotthlive.v1.Event",
			Field:     "name",
			Predicate: "len(this) > 0 && len(this) <= 64 && matches(this, `^[a-z][a-z0-9_.:-]*$`)",
			Value:     message.Name,
		}
	}
	if !(len(message.FragmentId) > 0 && len(message.FragmentId) <= 64 && _liquidEventFragmentIdRe0.MatchString(message.FragmentId)) {
		return &liquidproto.Error{
			Message:   "gotthlive.v1.Event",
			Field:     "fragment_id",
			Predicate: "len(this) > 0 && len(this) <= 64 && matches(this, `^[A-Za-z0-9_:.-]+$`)",
			Value:     message.FragmentId,
		}
	}
	if !(message.SeenServerSeq > 0) {
		return &liquidproto.Error{
			Message:   "gotthlive.v1.Event",
			Field:     "seen_server_seq",
			Predicate: "this > 0",
			Value:     message.SeenServerSeq,
		}
	}
	return nil
}

// ValidateEventField validates Liquid Proto field predicates.
func ValidateEventField(message *EventField) error {
	if message == nil {
		return fmt.Errorf("ValidateEventField: nil *EventField")
	}
	if !(len(message.Key) > 0 && len(message.Key) <= 128 && _liquidEventFieldKeyRe0.MatchString(message.Key)) {
		return &liquidproto.Error{
			Message:   "gotthlive.v1.EventField",
			Field:     "key",
			Predicate: "len(this) > 0 && len(this) <= 128 && matches(this, `^[A-Za-z0-9_.\\[\\]-]+$`)",
			Value:     message.Key,
		}
	}
	if !(len(message.Value) <= 8192) {
		return &liquidproto.Error{
			Message:   "gotthlive.v1.EventField",
			Field:     "value",
			Predicate: "len(this) <= 8192",
			Value:     message.Value,
		}
	}
	return nil
}

// ValidateAck validates Liquid Proto field predicates.
func ValidateAck(message *Ack) error {
	if message == nil {
		return fmt.Errorf("ValidateAck: nil *Ack")
	}
	if !(message.ServerSeq > 0) {
		return &liquidproto.Error{
			Message:   "gotthlive.v1.Ack",
			Field:     "server_seq",
			Predicate: "this > 0",
			Value:     message.ServerSeq,
		}
	}
	return nil
}

// ValidateResyncRequest validates Liquid Proto field predicates.
func ValidateResyncRequest(message *ResyncRequest) error {
	if message == nil {
		return fmt.Errorf("ValidateResyncRequest: nil *ResyncRequest")
	}
	if !(message.LastAppliedSeq > 0) {
		return &liquidproto.Error{
			Message:   "gotthlive.v1.ResyncRequest",
			Field:     "last_applied_seq",
			Predicate: "this > 0",
			Value:     message.LastAppliedSeq,
		}
	}
	return nil
}

// ValidateClientTelemetry validates Liquid Proto field predicates.
func ValidateClientTelemetry(message *ClientTelemetry) error {
	if message == nil {
		return fmt.Errorf("ValidateClientTelemetry: nil *ClientTelemetry")
	}
	if !(message.PatchId > 0) {
		return &liquidproto.Error{
			Message:   "gotthlive.v1.ClientTelemetry",
			Field:     "patch_id",
			Predicate: "this > 0",
			Value:     message.PatchId,
		}
	}
	if !(message.MorphMicros <= 60000000) {
		return &liquidproto.Error{
			Message:   "gotthlive.v1.ClientTelemetry",
			Field:     "morph_micros",
			Predicate: "this <= 60000000",
			Value:     message.MorphMicros,
		}
	}
	if !(message.ApplyMicros <= 60000000) {
		return &liquidproto.Error{
			Message:   "gotthlive.v1.ClientTelemetry",
			Field:     "apply_micros",
			Predicate: "this <= 60000000",
			Value:     message.ApplyMicros,
		}
	}
	return nil
}

// ValidatePatch validates Liquid Proto field predicates.
func ValidatePatch(message *Patch) error {
	if message == nil {
		return fmt.Errorf("ValidatePatch: nil *Patch")
	}
	if !(message.ServerSeq > 0) {
		return &liquidproto.Error{
			Message:   "gotthlive.v1.Patch",
			Field:     "server_seq",
			Predicate: "this > 0",
			Value:     message.ServerSeq,
		}
	}
	if !(message.PatchId > 0) {
		return &liquidproto.Error{
			Message:   "gotthlive.v1.Patch",
			Field:     "patch_id",
			Predicate: "this > 0",
			Value:     message.PatchId,
		}
	}
	if !(message.TransitionId > 0) {
		return &liquidproto.Error{
			Message:   "gotthlive.v1.Patch",
			Field:     "transition_id",
			Predicate: "this > 0",
			Value:     message.TransitionId,
		}
	}
	if !(message.StateVersion > 0) {
		return &liquidproto.Error{
			Message:   "gotthlive.v1.Patch",
			Field:     "state_version",
			Predicate: "this > 0",
			Value:     message.StateVersion,
		}
	}
	return nil
}

// ValidateSnapshot validates Liquid Proto field predicates.
func ValidateSnapshot(message *Snapshot) error {
	if message == nil {
		return fmt.Errorf("ValidateSnapshot: nil *Snapshot")
	}
	if !(message.ServerSeq > 0) {
		return &liquidproto.Error{
			Message:   "gotthlive.v1.Snapshot",
			Field:     "server_seq",
			Predicate: "this > 0",
			Value:     message.ServerSeq,
		}
	}
	if !(message.PatchId > 0) {
		return &liquidproto.Error{
			Message:   "gotthlive.v1.Snapshot",
			Field:     "patch_id",
			Predicate: "this > 0",
			Value:     message.PatchId,
		}
	}
	if !(message.TransitionId > 0) {
		return &liquidproto.Error{
			Message:   "gotthlive.v1.Snapshot",
			Field:     "transition_id",
			Predicate: "this > 0",
			Value:     message.TransitionId,
		}
	}
	if !(message.StateVersion > 0) {
		return &liquidproto.Error{
			Message:   "gotthlive.v1.Snapshot",
			Field:     "state_version",
			Predicate: "this > 0",
			Value:     message.StateVersion,
		}
	}
	if !(message.HeartbeatIntervalMs >= 1000 && message.HeartbeatIntervalMs <= 300000) {
		return &liquidproto.Error{
			Message:   "gotthlive.v1.Snapshot",
			Field:     "heartbeat_interval_ms",
			Predicate: "this >= 1000 && this <= 300000",
			Value:     message.HeartbeatIntervalMs,
		}
	}
	if !(message.MaxInboundFrameBytes >= 1024 && message.MaxInboundFrameBytes <= 1048576) {
		return &liquidproto.Error{
			Message:   "gotthlive.v1.Snapshot",
			Field:     "max_inbound_frame_bytes",
			Predicate: "this >= 1024 && this <= 1048576",
			Value:     message.MaxInboundFrameBytes,
		}
	}
	if !(message.AckWindow >= 1 && message.AckWindow <= 256) {
		return &liquidproto.Error{
			Message:   "gotthlive.v1.Snapshot",
			Field:     "ack_window",
			Predicate: "this >= 1 && this <= 256",
			Value:     message.AckWindow,
		}
	}
	return nil
}

// ValidateFragmentUpdate validates Liquid Proto field predicates.
func ValidateFragmentUpdate(message *FragmentUpdate) error {
	if message == nil {
		return fmt.Errorf("ValidateFragmentUpdate: nil *FragmentUpdate")
	}
	if !(len(message.FragmentId) > 0 && len(message.FragmentId) <= 64 && _liquidFragmentUpdateFragmentIdRe0.MatchString(message.FragmentId)) {
		return &liquidproto.Error{
			Message:   "gotthlive.v1.FragmentUpdate",
			Field:     "fragment_id",
			Predicate: "len(this) > 0 && len(this) <= 64 && matches(this, `^[A-Za-z0-9_:.-]+$`)",
			Value:     message.FragmentId,
		}
	}
	if !(len(message.Html) <= 1048576) {
		return &liquidproto.Error{
			Message:   "gotthlive.v1.FragmentUpdate",
			Field:     "html",
			Predicate: "len(this) <= 1048576",
			Value:     message.Html,
		}
	}
	return nil
}

// ValidateOrigin validates Liquid Proto field predicates.
func ValidateOrigin(message *Origin) error {
	if message == nil {
		return fmt.Errorf("ValidateOrigin: nil *Origin")
	}
	if !(len(message.Source) > 0 && len(message.Source) <= 64 && _liquidOriginSourceRe0.MatchString(message.Source)) {
		return &liquidproto.Error{
			Message:   "gotthlive.v1.Origin",
			Field:     "source",
			Predicate: "len(this) > 0 && len(this) <= 64 && matches(this, `^[a-z][a-z0-9_.:/-]*$`)",
			Value:     message.Source,
		}
	}
	return nil
}

// ValidateError validates Liquid Proto field predicates.
func ValidateError(message *Error) error {
	if message == nil {
		return fmt.Errorf("ValidateError: nil *Error")
	}
	if !(len(message.Message) <= 512) {
		return &liquidproto.Error{
			Message:   "gotthlive.v1.Error",
			Field:     "message",
			Predicate: "len(this) <= 512",
			Value:     message.Message,
		}
	}
	return nil
}

// ValidateHeartbeat validates Liquid Proto field predicates.
func ValidateHeartbeat(message *Heartbeat) error {
	if message == nil {
		return fmt.Errorf("ValidateHeartbeat: nil *Heartbeat")
	}
	if !(message.Nonce > 0) {
		return &liquidproto.Error{
			Message:   "gotthlive.v1.Heartbeat",
			Field:     "nonce",
			Predicate: "this > 0",
			Value:     message.Nonce,
		}
	}
	if !(message.IntervalMs >= 1000 && message.IntervalMs <= 300000) {
		return &liquidproto.Error{
			Message:   "gotthlive.v1.Heartbeat",
			Field:     "interval_ms",
			Predicate: "this >= 1000 && this <= 300000",
			Value:     message.IntervalMs,
		}
	}
	return nil
}
