// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/candacelabs/candace/services/candaceos/operator (interfaces: Reconciler)
//
// Generated by this command:
//
//	mockgen -destination=mock_reconciler_test.go -package=operator_test github.com/candacelabs/candace/services/candaceos/operator Reconciler
//

// Package operator_test is a generated GoMock package.
package operator_test

import (
	context "context"
	reflect "reflect"

	candaceosv1 "github.com/candacelabs/candace/proto/candace/candaceos/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockReconciler is a mock of Reconciler interface.
type MockReconciler struct {
	ctrl     *gomock.Controller
	recorder *MockReconcilerMockRecorder
	isgomock struct{}
}

// MockReconcilerMockRecorder is the mock recorder for MockReconciler.
type MockReconcilerMockRecorder struct {
	mock *MockReconciler
}

// NewMockReconciler creates a new mock instance.
func NewMockReconciler(ctrl *gomock.Controller) *MockReconciler {
	mock := &MockReconciler{ctrl: ctrl}
	mock.recorder = &MockReconcilerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReconciler) EXPECT() *MockReconcilerMockRecorder {
	return m.recorder
}

// Prepare mocks base method.
func (m *MockReconciler) Prepare(ctx context.Context, intent *candaceosv1.ReconcileIntent) (*candaceosv1.ReconcileRevision, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Prepare", ctx, intent)
	ret0, _ := ret[0].(*candaceosv1.ReconcileRevision)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Prepare indicates an expected call of Prepare.
func (mr *MockReconcilerMockRecorder) Prepare(ctx, intent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Prepare", reflect.TypeOf((*MockReconciler)(nil).Prepare), ctx, intent)
}

// ReconcileApproved mocks base method.
func (m *MockReconciler) ReconcileApproved(ctx context.Context, intent *candaceosv1.ReconcileIntent, revision *candaceosv1.ReconcileRevision) (*candaceosv1.ReconcileEvidence, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReconcileApproved", ctx, intent, revision)
	ret0, _ := ret[0].(*candaceosv1.ReconcileEvidence)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReconcileApproved indicates an expected call of ReconcileApproved.
func (mr *MockReconcilerMockRecorder) ReconcileApproved(ctx, intent, revision any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReconcileApproved", reflect.TypeOf((*MockReconciler)(nil).ReconcileApproved), ctx, intent, revision)
}
