// Code generated by MockGen. DO NOT EDIT.
// Source: api_cgen.go
//
// Generated by this command:
//
//	mockgen -source=api_cgen.go -destination=internal/mocks/api.gen.go -package=csfmocks
//

// Package csfmocks is a generated GoMock package.
package csfmocks

import (
	context "context"
	reflect "reflect"

	brainspinev1 "github.com/candacelabs/candace/proto/candace/brainspine/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockIResearch is a mock of IResearch interface.
type MockIResearch struct {
	ctrl     *gomock.Controller
	recorder *MockIResearchMockRecorder
	isgomock struct{}
}

// MockIResearchMockRecorder is the mock recorder for MockIResearch.
type MockIResearchMockRecorder struct {
	mock *MockIResearch
}

// NewMockIResearch creates a new mock instance.
func NewMockIResearch(ctrl *gomock.Controller) *MockIResearch {
	mock := &MockIResearch{ctrl: ctrl}
	mock.recorder = &MockIResearchMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIResearch) EXPECT() *MockIResearchMockRecorder {
	return m.recorder
}

// CancelSimulation mocks base method.
func (m *MockIResearch) CancelSimulation(ctx context.Context, request *brainspinev1.CancelSimulationRequest) (*brainspinev1.CancelSimulationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelSimulation", ctx, request)
	ret0, _ := ret[0].(*brainspinev1.CancelSimulationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelSimulation indicates an expected call of CancelSimulation.
func (mr *MockIResearchMockRecorder) CancelSimulation(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelSimulation", reflect.TypeOf((*MockIResearch)(nil).CancelSimulation), ctx, request)
}

// Compile mocks base method.
func (m *MockIResearch) Compile(ctx context.Context, request *brainspinev1.CompileRequest) (*brainspinev1.CompileResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Compile", ctx, request)
	ret0, _ := ret[0].(*brainspinev1.CompileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Compile indicates an expected call of Compile.
func (mr *MockIResearchMockRecorder) Compile(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Compile", reflect.TypeOf((*MockIResearch)(nil).Compile), ctx, request)
}

// GetDocument mocks base method.
func (m *MockIResearch) GetDocument(ctx context.Context, request *brainspinev1.GetDocumentRequest) (*brainspinev1.GetDocumentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDocument", ctx, request)
	ret0, _ := ret[0].(*brainspinev1.GetDocumentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDocument indicates an expected call of GetDocument.
func (mr *MockIResearchMockRecorder) GetDocument(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDocument", reflect.TypeOf((*MockIResearch)(nil).GetDocument), ctx, request)
}

// GetGraph mocks base method.
func (m *MockIResearch) GetGraph(ctx context.Context, request *brainspinev1.GetGraphRequest) (*brainspinev1.GetGraphResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGraph", ctx, request)
	ret0, _ := ret[0].(*brainspinev1.GetGraphResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGraph indicates an expected call of GetGraph.
func (mr *MockIResearchMockRecorder) GetGraph(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGraph", reflect.TypeOf((*MockIResearch)(nil).GetGraph), ctx, request)
}

// GetSnapshot mocks base method.
func (m *MockIResearch) GetSnapshot(ctx context.Context, request *brainspinev1.GetSnapshotRequest) (*brainspinev1.GetSnapshotResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSnapshot", ctx, request)
	ret0, _ := ret[0].(*brainspinev1.GetSnapshotResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSnapshot indicates an expected call of GetSnapshot.
func (mr *MockIResearchMockRecorder) GetSnapshot(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSnapshot", reflect.TypeOf((*MockIResearch)(nil).GetSnapshot), ctx, request)
}

// GetWorkbenchTheme mocks base method.
func (m *MockIResearch) GetWorkbenchTheme(ctx context.Context, request *brainspinev1.GetWorkbenchThemeRequest) (*brainspinev1.GetWorkbenchThemeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkbenchTheme", ctx, request)
	ret0, _ := ret[0].(*brainspinev1.GetWorkbenchThemeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkbenchTheme indicates an expected call of GetWorkbenchTheme.
func (mr *MockIResearchMockRecorder) GetWorkbenchTheme(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkbenchTheme", reflect.TypeOf((*MockIResearch)(nil).GetWorkbenchTheme), ctx, request)
}

// IngestDocument mocks base method.
func (m *MockIResearch) IngestDocument(ctx context.Context, request *brainspinev1.IngestDocumentRequest) (*brainspinev1.IngestDocumentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IngestDocument", ctx, request)
	ret0, _ := ret[0].(*brainspinev1.IngestDocumentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IngestDocument indicates an expected call of IngestDocument.
func (mr *MockIResearchMockRecorder) IngestDocument(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IngestDocument", reflect.TypeOf((*MockIResearch)(nil).IngestDocument), ctx, request)
}

// InspectSimulation mocks base method.
func (m *MockIResearch) InspectSimulation(ctx context.Context, request *brainspinev1.InspectSimulationRequest) (*brainspinev1.InspectSimulationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InspectSimulation", ctx, request)
	ret0, _ := ret[0].(*brainspinev1.InspectSimulationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InspectSimulation indicates an expected call of InspectSimulation.
func (mr *MockIResearchMockRecorder) InspectSimulation(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InspectSimulation", reflect.TypeOf((*MockIResearch)(nil).InspectSimulation), ctx, request)
}

// ListSimulations mocks base method.
func (m *MockIResearch) ListSimulations(ctx context.Context, request *brainspinev1.ListSimulationsRequest) (*brainspinev1.ListSimulationsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSimulations", ctx, request)
	ret0, _ := ret[0].(*brainspinev1.ListSimulationsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSimulations indicates an expected call of ListSimulations.
func (mr *MockIResearchMockRecorder) ListSimulations(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSimulations", reflect.TypeOf((*MockIResearch)(nil).ListSimulations), ctx, request)
}

// PrepareAgentAssignment mocks base method.
func (m *MockIResearch) PrepareAgentAssignment(ctx context.Context, request *brainspinev1.PrepareAgentAssignmentRequest) (*brainspinev1.PrepareAgentAssignmentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrepareAgentAssignment", ctx, request)
	ret0, _ := ret[0].(*brainspinev1.PrepareAgentAssignmentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PrepareAgentAssignment indicates an expected call of PrepareAgentAssignment.
func (mr *MockIResearchMockRecorder) PrepareAgentAssignment(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrepareAgentAssignment", reflect.TypeOf((*MockIResearch)(nil).PrepareAgentAssignment), ctx, request)
}

// PutEdge mocks base method.
func (m *MockIResearch) PutEdge(ctx context.Context, request *brainspinev1.PutEdgeRequest) (*brainspinev1.PutEdgeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutEdge", ctx, request)
	ret0, _ := ret[0].(*brainspinev1.PutEdgeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutEdge indicates an expected call of PutEdge.
func (mr *MockIResearchMockRecorder) PutEdge(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutEdge", reflect.TypeOf((*MockIResearch)(nil).PutEdge), ctx, request)
}

// PutNode mocks base method.
func (m *MockIResearch) PutNode(ctx context.Context, request *brainspinev1.PutNodeRequest) (*brainspinev1.PutNodeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutNode", ctx, request)
	ret0, _ := ret[0].(*brainspinev1.PutNodeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutNode indicates an expected call of PutNode.
func (mr *MockIResearchMockRecorder) PutNode(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutNode", reflect.TypeOf((*MockIResearch)(nil).PutNode), ctx, request)
}

// ReadSimulationLogs mocks base method.
func (m *MockIResearch) ReadSimulationLogs(ctx context.Context, request *brainspinev1.ReadSimulationLogsRequest) (*brainspinev1.ReadSimulationLogsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadSimulationLogs", ctx, request)
	ret0, _ := ret[0].(*brainspinev1.ReadSimulationLogsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadSimulationLogs indicates an expected call of ReadSimulationLogs.
func (mr *MockIResearchMockRecorder) ReadSimulationLogs(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadSimulationLogs", reflect.TypeOf((*MockIResearch)(nil).ReadSimulationLogs), ctx, request)
}

// RebuildSimulationTrace mocks base method.
func (m *MockIResearch) RebuildSimulationTrace(ctx context.Context, request *brainspinev1.RebuildSimulationTraceRequest) (*brainspinev1.RebuildSimulationTraceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RebuildSimulationTrace", ctx, request)
	ret0, _ := ret[0].(*brainspinev1.RebuildSimulationTraceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RebuildSimulationTrace indicates an expected call of RebuildSimulationTrace.
func (mr *MockIResearchMockRecorder) RebuildSimulationTrace(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RebuildSimulationTrace", reflect.TypeOf((*MockIResearch)(nil).RebuildSimulationTrace), ctx, request)
}

// RecordSimulationEvents mocks base method.
func (m *MockIResearch) RecordSimulationEvents(ctx context.Context, request *brainspinev1.RecordSimulationEventsRequest) (*brainspinev1.RecordSimulationEventsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordSimulationEvents", ctx, request)
	ret0, _ := ret[0].(*brainspinev1.RecordSimulationEventsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecordSimulationEvents indicates an expected call of RecordSimulationEvents.
func (mr *MockIResearchMockRecorder) RecordSimulationEvents(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordSimulationEvents", reflect.TypeOf((*MockIResearch)(nil).RecordSimulationEvents), ctx, request)
}

// ReloadWorkbenchTheme mocks base method.
func (m *MockIResearch) ReloadWorkbenchTheme(ctx context.Context, request *brainspinev1.ReloadWorkbenchThemeRequest) (*brainspinev1.ReloadWorkbenchThemeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReloadWorkbenchTheme", ctx, request)
	ret0, _ := ret[0].(*brainspinev1.ReloadWorkbenchThemeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReloadWorkbenchTheme indicates an expected call of ReloadWorkbenchTheme.
func (mr *MockIResearchMockRecorder) ReloadWorkbenchTheme(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReloadWorkbenchTheme", reflect.TypeOf((*MockIResearch)(nil).ReloadWorkbenchTheme), ctx, request)
}

// Search mocks base method.
func (m *MockIResearch) Search(ctx context.Context, request *brainspinev1.SearchRequest) (*brainspinev1.SearchResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, request)
	ret0, _ := ret[0].(*brainspinev1.SearchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockIResearchMockRecorder) Search(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockIResearch)(nil).Search), ctx, request)
}

// SubmitSimulation mocks base method.
func (m *MockIResearch) SubmitSimulation(ctx context.Context, request *brainspinev1.SubmitSimulationRequest) (*brainspinev1.SubmitSimulationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitSimulation", ctx, request)
	ret0, _ := ret[0].(*brainspinev1.SubmitSimulationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubmitSimulation indicates an expected call of SubmitSimulation.
func (mr *MockIResearchMockRecorder) SubmitSimulation(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitSimulation", reflect.TypeOf((*MockIResearch)(nil).SubmitSimulation), ctx, request)
}
