// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/candacelabs/candace/services/candaceos/httpapi (interfaces: Backend)
//
// Generated by this command:
//
//	mockgen -destination=mock_backend_test.go -package=httpapi_test github.com/candacelabs/candace/services/candaceos/httpapi Backend
//

// Package httpapi_test is a generated GoMock package.
package httpapi_test

import (
	context "context"
	reflect "reflect"

	candaceosv1 "github.com/candacelabs/candace/proto/candace/candaceos/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockBackend is a mock of Backend interface.
type MockBackend struct {
	ctrl     *gomock.Controller
	recorder *MockBackendMockRecorder
	isgomock struct{}
}

// MockBackendMockRecorder is the mock recorder for MockBackend.
type MockBackendMockRecorder struct {
	mock *MockBackend
}

// NewMockBackend creates a new mock instance.
func NewMockBackend(ctrl *gomock.Controller) *MockBackend {
	mock := &MockBackend{ctrl: ctrl}
	mock.recorder = &MockBackendMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBackend) EXPECT() *MockBackendMockRecorder {
	return m.recorder
}

// Abort mocks base method.
func (m *MockBackend) Abort(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Abort", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Abort indicates an expected call of Abort.
func (mr *MockBackendMockRecorder) Abort(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Abort", reflect.TypeOf((*MockBackend)(nil).Abort), ctx)
}

// AbortRun mocks base method.
func (m *MockBackend) AbortRun(ctx context.Context, sessionID, runID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AbortRun", ctx, sessionID, runID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AbortRun indicates an expected call of AbortRun.
func (mr *MockBackendMockRecorder) AbortRun(ctx, sessionID, runID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AbortRun", reflect.TypeOf((*MockBackend)(nil).AbortRun), ctx, sessionID, runID)
}

// Health mocks base method.
func (m *MockBackend) Health(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Health", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Health indicates an expected call of Health.
func (mr *MockBackendMockRecorder) Health(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Health", reflect.TypeOf((*MockBackend)(nil).Health), ctx)
}

// ResolveApproval mocks base method.
func (m *MockBackend) ResolveApproval(id, decision string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveApproval", id, decision)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResolveApproval indicates an expected call of ResolveApproval.
func (mr *MockBackendMockRecorder) ResolveApproval(id, decision any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveApproval", reflect.TypeOf((*MockBackend)(nil).ResolveApproval), id, decision)
}

// Send mocks base method.
func (m *MockBackend) Send(ctx context.Context, prompt string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, prompt)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Send indicates an expected call of Send.
func (mr *MockBackendMockRecorder) Send(ctx, prompt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockBackend)(nil).Send), ctx, prompt)
}

// SendToClaw mocks base method.
func (m *MockBackend) SendToClaw(ctx context.Context, sessionID, expectedRunID, prompt string, delivery candaceosv1.HarnessDelivery) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendToClaw", ctx, sessionID, expectedRunID, prompt, delivery)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendToClaw indicates an expected call of SendToClaw.
func (mr *MockBackendMockRecorder) SendToClaw(ctx, sessionID, expectedRunID, prompt, delivery any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendToClaw", reflect.TypeOf((*MockBackend)(nil).SendToClaw), ctx, sessionID, expectedRunID, prompt, delivery)
}

// Snapshot mocks base method.
func (m *MockBackend) Snapshot(ctx context.Context) (*candaceosv1.WebUISnapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Snapshot", ctx)
	ret0, _ := ret[0].(*candaceosv1.WebUISnapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Snapshot indicates an expected call of Snapshot.
func (mr *MockBackendMockRecorder) Snapshot(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Snapshot", reflect.TypeOf((*MockBackend)(nil).Snapshot), ctx)
}

// Subscribe mocks base method.
func (m *MockBackend) Subscribe() (<-chan struct{}, func()) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe")
	ret0, _ := ret[0].(<-chan struct{})
	ret1, _ := ret[1].(func())
	return ret0, ret1
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockBackendMockRecorder) Subscribe() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockBackend)(nil).Subscribe))
}
